/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewSet: typeof import('./src/components/AddNewSet.vue')['default']
    Karussell: typeof import('./src/components/Karussell.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    SearchBrick: typeof import('./src/components/SearchBrick.vue')['default']
    SearchResultView: typeof import('./src/components/SearchResultView.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    Website: typeof import('./src/components/Website.vue')['default']
  }
}
