/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Device: typeof import('./src/components/Device.vue')['default']
    Expansionpanel: typeof import('./src/components/Expansionpanel.vue')['default']
    Helloorld: typeof import('./src/components/Helloorld.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SearchBrick: typeof import('./src/components/SearchBrick.vue')['default']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
    SearchResultView: typeof import('./src/components/SearchResultView.vue')['default']
    Website: typeof import('./src/components/Website.vue')['default']
  }
}
